config:
  credentials: []
  project_repos:
    github.com/EGI-Federation/eosc-data-transfer:
      branch: main
      repo: https://github.com/EGI-Federation/eosc-data-transfer
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EGI-Federation/eosc-data-transfer git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-amaranth-shrew.sh
        container: qc.acc_chummy-eggplant-turtle
  QC.Doc:
    repos:
      github.com/EGI-Federation/eosc-data-transfer find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-puce-foxhound.sh
        container: qc.doc_stinky-olivine-fish
      github.com/EGI-Federation/eosc-data-transfer git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-cobalt-stingray.sh
        container: qc.doc_homey-orange-beaver
      github.com/EGI-Federation/eosc-data-transfer markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-carmine-bordeaux.sh
        container: qc.doc_skanky-bronze-panda
  QC.Lic:
    repos:
      github.com/EGI-Federation/eosc-data-transfer licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cyan-newfoundland.sh
        container: qc.lic_lovely-gold-chamois
  QC.Met:
    repos:
      github.com/EGI-Federation/eosc-data-transfer cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-gamboge-corgi.sh
        container: qc.met_randy-red-setter
  QC.Sty:
    repos:
      github.com/EGI-Federation/eosc-data-transfer checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cinnamon-bee.sh
        container: qc.sty_hilly-pink-sheep
      github.com/EGI-Federation/eosc-data-transfer hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-white-heron.sh
        container: qc.sty_squeaky-malachite-boar
      github.com/EGI-Federation/eosc-data-transfer jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-chartreuse-dogfish.sh
        container: qc.sty_woozy-blue-grasshopper
  QC.Ver:
    repos:
      github.com/EGI-Federation/eosc-data-transfer get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-peach-cuttlefish.sh
        container: qc.ver_messy-eggplant-axolotl
timeout: 5400
